app = "actionboard-example"

kill_signal = "SIGINT"
kill_timeout = 60
processes = []

[build]
   image = "ghcr.io/markdessain/actionboard:0.1.13"

[experimental]
    cmd = [
        "--port=8080",
        "--repository=tiangolo/fastapi",
        "--repository=apache/spark",
        "--days=3"
    ]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"