name: Build

on:
  push:
    branches:
      - '*'

permissions: write-all

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.0

      - name: Build Linux 64bit
        run: |
          GOOS=linux GOARCH=amd64 go build ./main.go

  build_mac:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.0

      - name: Build Linux 64bit
        run: |
          GOOS=windows GOARCH=amd64 go build ./main.go

  build_window:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.0

      - name: Build Windows 64bit
        run: |
          GOOS=windows GOARCH=amd64 go build ./main.go
